#!/usr/bin/env bash
set -eou pipefail

cd $(git rev-parse --show-toplevel)

source scripts/env

./scripts/build

trap "docker compose down" SIGINT

echo '+++ Stack up +++'
docker compose \
       --file docker/docker-compose.yaml \
       --project-directory $(pwd) \
       up
